module.exports.authController = require('./auth.controller');
module.exports.adminController = require('./admin.controller');
module.exports.userController = require('./user.controller');
module.exports.contactUsController = require('./contactUs.controller');
module.exports.notificationController=require('./notifications.controller');
module.exports.registerController=require('./register.controller')
module.exports.productController=require('./product.controller')
module.exports.wishlistController=require('./wishlist.controller')
module.exports.categoryController=require('./category.controller')
module.exports.orderDetailsController=require('./orderDetails.controller')
module.exports.orderController=require('./order.controller')
module.exports.paymentController=require('./payment.controller')
module.exports.priceFilterController=require('./priceFilter.controller');
module.exports.customJewelsController=require('./customJewels.controller');
module.exports.giftingGuideController=require('./giftingGuide.controller');
module.exports.newArrivalsController=require('./newArrivals.controller');
module.exports.blogsController=require('./blogs.controller');
module.exports.aboutUsController=require('./aboutUs.controller');
module.exports.reviewController=require('./review.controller');
module.exports.metalController=require('./metal.controller');
module.exports.diamondShapeController=require('./diamondShape.controller');
module.exports.shankController=require('./shank.controller');

