module.exports.Token = require('./token.model');
module.exports.Admin = require('./admin.model');
module.exports.User = require('./user.model');
module.exports.AboutUs = require('./aboutUs.model');
module.exports.Notification=require('./notification.model');
module.exports.ContactUs = require('./contact.model');
module.exports.Register=require('./register.modal')
module.exports.Products=require('./products.modal')
module.exports.Wishlist=require('./wishlist.modal')
module.exports.Cart=require('./cart.modal')
module.exports.Category=require('./category.model')
module.exports.OrderDetails=require('./orderDetails.model')
module.exports.Order=require('./order.model')
module.exports.Counter=require('./counter.model')
module.exports.ProductVariations=require('./productVariation.model')
module.exports.CustomJewels=require('./customJewels.model')
module.exports.PriceFilter=require('./priceFilter.model')
